### ISSUE TITLE
Multi sample analysis

### ISSUE THREAD

**Issue by Jihua-Liu** [tansey-lab/bayestme#108]
Hi! I wonder can bayestme support multi-sample analysis? Like do deconvolution for two ST datasets at the same time. 
Thank you!

**Comment by tansey** [comment]
Hi JJ, we're working on that and plan to release it in v2 along with the computational speedups. It's not terribly difficult but is a nontrivial extension.

**Comment by Jihua-Liu** [comment]
Thanks! I'm looking forward to V2 updates!
