### ISSUE TITLE
spatial transcriptional program plot Interpretation

### ISSUE THREAD

**Issue by JihyunKiminGithub** [tansey-lab/bayestme#49]
Dear bayestme developers,

I am having hard time to interpret plots from bayesTME plot_spatial_expression.
The plots from bayestme seems to be completely reversed to the plots from seurat featureplot.
I understood that bayestme plots show part of the expression since it is celltype 6.
But can you please explain me the reasons for the reverse pattern of these results?

![image](https://user-images.githubusercontent.com/105287433/183305227-0efaaca9-d6e2-4c9e-b509-73baca4ae125.png)

![image](https://user-images.githubusercontent.com/105287433/183305230-900ee947-0295-4b77-a97b-dd66d1920e5e.png)

Thank you for making this amazing analysis tool.

Best,
Jihyun.

**Comment by tansey** [comment]
Hi Jihyun,

The difference here is that the spatial programs on the left tell you how many transcripts per cell of cell type 6 are expressed on average in each spot. On the right it's (i think) just a simple plot of the total reads in aggregate. That aggregate count conflates together several signals: which cell types are in the spot, how many of each cell type there are, and any variable expression levels. The spatial programs are trying to give you a distilled picture of spatial variation at the single cell level for a specific cell type.

**Comment by JihyunKiminGithub** [comment]
Dear BayesTME developers,

Thank you for the detailed explanation. This is very helpful.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/105287433/183470138-d2f358ad-858c-4106-8856-caa9628a4541.png">

I am having hard time interpreting this plot and would be grateful if you could kindly spend time explaining. I read over your manuscript but still did not get it.
In this plot, i am seeing several genes with colored circles and a color scale that runs from red to blue. How am I supposed to interpret the feature plot? is this a plot with module scores of genes listed?

Thank you,
Jihyun

**Comment by JihyunKiminGithub** [comment]
Hi jeffquinn,

Thank you for your detailed explanation. It was really helpful for proceeding my analysis.

I have a few more questions.
[1] What is the meaning of the under expression? I want to know what would be the meaning of spatial program negative scores.. I believe this could mean spatial program average expression of this blue area have less average expression of "rest of the genes" at this area.. Or If this scale was z-transformed score, It just could mean it is comparaively has lower average expression scores compared to red zone in the plots. Or Do I need to include "gray zone" to understand this expression pattern??
[2] What is the meaning of the circle size?
[3] How those genes are ordered? I assume it might have been arranged by average expression..

Thank you,
Jihyun

**Comment by JihyunKiminGithub** [comment]
Thank you so much for your detailed explanation.

I have two more questions about spatial program interpretation, especially color scale bar.

[1] Like the plots below, each program have different color scales. Can we think program with variable color scales (eg. 1~30) is probably more significant/influential program than the program with constant color scale(0~1.2)?

<img width="421" alt="image" src="https://user-images.githubusercontent.com/105287433/184888403-38ac795f-3d2e-414a-8208-35309b20a609.png">

[2]  If we use the function (spatial_expression.plot_spatial_pattern_and_all_constituent_genes), It gives us all the genes included in each program. Can I think genes with wide color scale is probably more influential to the program than the gene with narrow scales?

Thank you,
Jihyun

**Comment by tansey** [comment]
I'm not sure if I would necessarily say that there's a connection between the degree of spatial variation in genes within a program nor the spatial variation of a program among other programs relates to significance or influence. It's certainly possible that cells are more robust to the changes in some genes than others; so a small change in a gene's transcription level could have a much larger phenotypic effect than a large change in a less sensitive gene. Similarly, a program may have a smaller range of variation but there may be more statistical evidence for that range than for a wider range in another program. The correct statistical interpretation is that each of these genes/programs is significant at the target alpha FDR level. Comparisons amongst them in terms of more/less significance or influence would be a statement you would have to make based on biological knowledge of the genes and tissue.

**Comment by JihyunKiminGithub** [comment]
Thank you for your feedback.

It was really helpful.

Have a great day,
Jihyun
