### ISSUE TITLE
Question regarding phenotype_selection

### ISSUE THREAD

**Issue by JihyunKiminGithub** [tansey-lab/bayestme#52]
Dear BayesTME developers,

Thank you very much again for sharing this software. This is working seamlessly.
I have one quick question regarding the "phenotype_selection" command. 
I initially tried M-fold cross-validation with "python" implementation to determine the suggested number of cell types and lambda but it took too long so I gave up. 
Instead, command-line ran through generating a folder with a bunch of fold#.h5ad files but did not output the optimal number of cell types and lambda.
Is it possible to get the # of suggested cell types and lambda out of the folder/files generated by "phenotype_selection"?
I will appreciate it if you could kindly offer help.

Best,
Jihyun

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/105287433/183467558-412d2983-75e0-49ef-a392-02b5a4c091e5.png">

**Comment by tansey** [comment]
Hi Jihyun,

Adding to what Jeff said: if you would like to pick a lambda value, usually we find lambda=1000 to be fairly robust. You're then free to choose the number of cell types that make the most sense to you or to try each one and eyeball what makes sense. There's no way of knowing for sure what the right number is, so even our cross-validation routine is just an educated guess.

If you have paired scRNA from the same tissue, we have a workflow for incorporating that so you don't need to run the cross-validation.

Alternatively, if you have a scRNA atlas from the same type of tissue, but don't have paired scRNA for this specific sample, we're working on adding that workflow and would be happy to test it on your use case if you'd like.

**Comment by JihyunKiminGithub** [comment]
Dear jeffquinn and tansey,

Thank you for your detailed explanation.
It was really helpful.

Best,
Jihyun
