### ISSUE TITLE
`sample_mvn_from_precision` throws exception during Spatial Differential Expression sampling routine 

### ISSUE THREAD

**Issue by jeffquinn-msk** [tansey-lab/bayestme#56]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/105287433/184516373-0ae392a3-2972-4adc-abc7-94943cb00988.png">

Dear developers,

I am continuously getting this same error messages at some sample & some condition when I ran this code. (eg. spatial_expression --dataset 19_D_2_MIC_filtered_stdata_100.h5ad  --deconvolve-results Deconvolution_10_final.h5ad  --output Spatial_Expression_10_final.h5ad --n-spatial-patterns 10  --n-samples 1000 --n-burn 100 --n-thin 1 --simple --lam2 1000 --n-gene 100)
Why this error pops up?? Do I need to re-calculate deconvolution object? or Do I need to change some parameters?

Best,
Jihyun

_Originally posted by @JihyunKiminGithub in https://github.com/tansey-lab/bayestme/issues/48#issuecomment-1214245007_

**Comment by JihyunKiminGithub** [comment]
Hi Jeffquinn,

Thank you for your quick feedback.
I will share SpatialExpressionDataset object which is bleed corrected until tomorrow. Deconvolution object is too big to share with you. The oddest thing is spatial_expression is calculated well at some parameter k (k=5) but not when (k=10, 11, 15 etc..).

I will get back to you soon!
Thank you,
Jihyun

**Comment by JihyunKiminGithub** [comment]
Hi all,

I attached bayestme object through google drive.
I only shared this with (tanseyw@mskcc.org,wes.tansey@gmail.com) whom I could find email address.

link: https://drive.google.com/drive/folders/13x1OmHM_xOIhMvVVYfr6vSCc08IayvI_?usp=sharing

Thank you,
Jihyun

**Comment by JihyunKiminGithub** [comment]
I also attached this code to the drive.
If you want to directly access to the google drive, please let me know your email.

Thank you,
Jihyun

# Deconvolution Codes #

deconvolve --input 19_D_2_HGD_filtered_stdata_100.h5ad --output Deconvolution_10.h5ad --n-gene 100 --n-components 10 --lam2 1000 --n-samples 1000 --n-burnin 100 --n-thin 1 --random-seed  20220807
deconvolve --input 19_D_2_HGD_filtered_stdata_100.h5ad --output Deconvolution_15.h5ad --n-gene 100 --n-components 15 --lam2 1000 --n-samples 1000 --n-burnin 100 --n-thin 1 --random-seed  20220807

# Spatial Expression Code: which gave me errors #

spatial_expression --dataset 19_D_2_HGD_filtered_stdata_100.h5ad  --deconvolve-results Deconvolution_10.h5ad  --output Spatial_Expression_10.h5ad --n-spatial-patterns 10  --n-samples 1000 --n-burn 100 --n-thin 1 --simple --lam2 1000 --n-gene 100

spatial_expression --dataset 19_D_2_HGD_filtered_stdata_100.h5ad  --deconvolve-results Deconvolution_15.h5ad  --output Spatial_Expression_15.h5ad --n-spatial-patterns 10  --n-samples 1000 --n-burn 100 --n-thin 1 --simple --lam2 1000 --n-gene 100

**Comment by JihyunKiminGithub** [comment]
Thank you so much jeff,

I would open this again if I need those results or face similar errors.

Best,
Jihyun
